export enum URLS {
  LOCATIONS = "web/index.php/api/v2/admin/locations",
  JOB_TITLES = "web/index.php/api/v2/admin/job-titles",
  EMPLOYEES = "web/index.php/api/v2/pim/employees",
  JOB_DETAILS = "web/index.php/api/v2/pim/employees/",
  SALARY_COMPONENTS = "web/index.php/api/v2/pim/employees/",
  DEFINED_REPORTS = "web/index.php/api/v2/pim/reports/defined",
  VIEW_REPORT = "web/index.php/api/v2/pim/reports/data?reportId=",
  USERS = "/web/index.php/api/v2/admin/users",
  CLAIMS = "web/index.php/api/v2/claim/requests",
  SUBMIT_CLAIMS = "web/index.php/api/v2/claim/requests/",
  EVENTS = "web/index.php/api/v2/claim/events",
  EXPENSES = "web/index.php/api/v2/claim/requests/",
  EXPENSES_TYPES = "web/index.php/api/v2/claim/expenses/types",
  ADD_VACANCY = "web/index.php/api/v2/recruitment/vacancies",
  SHORT_LIST_CANDIDATE = "/web/index.php/api/v2/recruitment/candidates/",
  ADD_CANDIDATE = "/web/index.php/api/v2/recruitment/candidates",
  SCHEDULE_INTERVIEW = "web/index.php/api/v2/recruitment/candidates/",
  CNDIDATE_FORM= 'web/index.php/api/v2/recruitment/candidates/'
}
